db:
  host: "localhost"           # Имя сервиса базы данных в docker-compose
  port: 5432           # Порт базы данных
  user: "postgres"     # Имя пользователя базы данных
  password: "root"     # Пароль для базы данных
  dbname: "postgres"   # Имя базы данных
  sslmode: "disable"   # Режим SSL (отключен)
  search_path: "public" # Схема поиска (по умолчанию public)

server:
  ip: "0.0.0.0"        # IP-адрес сервера
  port: 8080           # Порт сервера
