name: Local CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Locally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker-compose down
          docker-compose up --build -d
