name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # 3. Установка зависимостей
      - name: Install dependencies
        run: go mod tidy

      # 4. Запуск тестов
      - name: Run tests
        run: go test ./... -v

      # 5. Линтинг кода (опционально)
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: run --timeout 5m
